export const menuItems = [
  {
    id: 1,
    itemName: 'Menu Item',
    subItems: [
      {
        subHeader: 'Header',
        subHeaderItems: [
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
        ],
      },
      {
        subHeader: 'Header',
        subHeaderItems: [
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
        ],
      },
    ],
  },
  {
    id: 2,
    itemName: 'Menu Item',
    subItems: [
      {
        subHeader: 'Header',
        subHeaderItems: [
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
        ],
      },
      {
        subHeader: 'Header',
        subHeaderItems: [
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
        ],
      },
    ],
  },
  {
    id: 3,
    itemName: 'Menu Item',
    subItems: [
      {
        subHeader: 'Header',
        subHeaderItems: [
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
        ],
      },
      {
        subHeader: 'Header',
        subHeaderItems: [
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
        ],
      },
    ],
  },
  {
    id: 4,
    itemName: 'Menu Item',
    subItems: [
      {
        subHeader: 'Header',
        subHeaderItems: [
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
        ],
      },
      {
        subHeader: 'Header',
        subHeaderItems: [
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
        ],
      },
    ],
  },
  {
    id: 5,
    itemName: 'Menu Item',
    subItems: [
      {
        subHeader: 'Header',
        subHeaderItems: [
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
        ],
      },
      {
        subHeader: 'Header',
        subHeaderItems: [
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
        ],
      },
    ],
  },
  {
    id: 6,
    itemName: 'Menu Item',
    subItems: [
      {
        subHeader: 'Header',
        subHeaderItems: [
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
        ],
      },
      {
        id: 6,
        subHeader: 'Header',
        subHeaderItems: [
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
        ],
      },
    ],
  },
  {
    id: 7,
    itemName: 'Menu Item',
    subItems: [
      {
        subHeader: 'Header',
        subHeaderItems: [
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
        ],
      },
      {
        subHeader: 'Header',
        subHeaderItems: [
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
        ],
      },
    ],
  },
  {
    id: 8,
    itemName: 'Menu Item',
    subItems: [
      {
        subHeader: 'Header',
        subHeaderItems: [
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
        ],
      },
      {
        subHeader: 'Header',
        subHeaderItems: [
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
        ],
      },
    ],
  },
  {
    id: 9,
    itemName: 'Menu Item',
    subItems: [
      {
        subHeader: 'Header',
        subHeaderItems: [
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
        ],
      },
      {
        subHeader: 'Header',
        subHeaderItems: [
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
        ],
      },
    ],
  },
  {
    id: 10,
    itemName: 'Menu Item',
    subItems: [
      {
        subHeader: 'Header',
        subHeaderItems: [
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
        ],
      },
      {
        subHeader: 'Header',
        subHeaderItems: [
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
        ],
      },
    ],
  },
  {
    id: 11,
    itemName: 'Menu Item',
    subItems: [
      {
        subHeader: 'Header',
        subHeaderItems: [
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
        ],
      },
      {
        subHeader: 'Header',
        subHeaderItems: [
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
        ],
      },
    ],
  },
  {
    id: 12,
    itemName: 'Menu Item',
    subItems: [
      {
        subHeader: 'Header',
        subHeaderItems: [
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
        ],
      },
      {
        subHeader: 'Header',
        subHeaderItems: [
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
          { subItemName: 'Subheader' },
        ],
      },
    ],
  },
];
